.\" An help of liveshell.
.TH LIVESHELL "1" "October 2015" "Wilddog Technologies" "User Commands"
.SH NAME
liveshell \- a tool to control your computer anywhere
.SH SYNOPSIS
.B liveshell
[\fIOPTION\fR] [\fIwilddog-url\fR] [\fIcallback-command\fR]
.SH DESCRIPTION
.\" Add any additional description here
.PP
Liveshell is an useful tool for users who want to control their computer anywhere.
.SH OPTIONS
.TP
\fB\-o\fR
origin data also will trigger your command
.TP
\fB\-s\fR
When the changed data is a string, the string will not analysised, and will in quotes, such as "string"
.TP
\fB\-v\fR
when triggered, print the command will be execute
.TP
\fB\-h\fR
Show help for all options
.\" .TP
.\" \fB\-\-version\fR
.\" Show current version of liveshell
.SH ARGUMENTS
.TP
\fBwilddog\-url\fR
An url of wilddog cloud, when it's value changed, liveshell will trigger the callback command, with the new value followed
.TP
\fBcallback\-command\fR
The command which you want trigger when value changed, such as command(ls, etc), or shell script.
.SH AUTHOR
Written by Baikal Hu and Jimmy Pan.
.SH "REPORTING BUGS"
Report bugs to jimmy.pan@wilddog.com
.SH COPYRIGHT
Copyright \(co 2015 Wilddog Technologies.
.br
License MIT: <http://wilddog.mit-license.org>.
.br
This is free software: you are free to change and redistribute it.
.br
There is NO WARRANTY, to the extent permitted by law.
